### ISSUE TITLE
AttributeError: 'AgentWorker' object has no attribute 'sess'

### ISSUE THREAD

**Issue by zhuliwen** [timediv/metagenrl#4]
KeyboardInterrupt
Failure # 1 (occurred at 2020-09-19_11-17-19)
Traceback (most recent call last):
  File "/home/csu/anaconda3/envs/metagenrl_zlw/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 420, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/csu/anaconda3/envs/metagenrl_zlw/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 358, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/csu/anaconda3/envs/metagenrl_zlw/lib/python3.6/site-packages/ray/worker.py", line 1458, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ^[[36mray_worker^[[39m (pid=52456, ip=162.105.95.245)
  File "python/ray/_raylet.pyx", line 606, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 613, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 614, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 599, in ray._raylet.execute_task.function_executor
  File "/home/csu/anaconda3/envs/metagenrl_zlw/lib/python3.6/site-packages/ray/tune/trainable.py", line 96, in __init__
    self._setup(copy.deepcopy(self.config))
  File "ray_experiments.py", line 55, in _setup
    self.obj_param_count = len(ray.get(params))
ray.exceptions.RayTaskError(AttributeError): ^[[36mray_worker^[[39m (pid=52462, ip=162.105.95.245)
  File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 599, in ray._raylet.execute_task.function_executor
  File "/home/csu/metagenrl/ray_workers.py", line 495, in get_objective_params
    return self.sess.run(self.locals.objective.variables)
AttributeError: 'AgentWorker' object has no attribute 'sess'

**Comment by louiskirsch** [comment]
Hi Zhuliwen,

can you have a look at the ray logs in `/tmp/ray`?
Also have a look at #2, perhaps you are using the wrong versions of the libraries.

**Comment by zhuliwen** [comment]
Hi @louiskirsch,

in the `logs` directory, 
- file `log_monitor.err` reports such an error:
```
OpenBLAS blas_thread_init: pthread_create failed for thread 37 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
...
...
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
```

- file `monitor.err` reports such an error:
```
<jemalloc>: arena 0 background thread creation failed (11)
```

- file `plasma_store.err` reports such an error:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0919 15:02:01.751008 17632 store.cc:1226] Allowing the Plasma store to use up to 1GB of memory.
I0919 15:02:01.751201 17632 store.cc:1253] Starting object store with directory /dev/shm and huge page support disabled
I0919 15:02:05.264618 17632 store.cc:1176] SIGTERM Signal received, closing Plasma Server...
```

- file `python-driver-01000000ffffffffffffffffffffffffffffffff20200919-150201.17459` reports such an error:
```
drwxrwxrwx 3 csu csu   4096 Oct 11 22:10 ./
Log file created at: 2020/09/19 15:02:01
Running on machine: optimus
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0919 15:02:01.973662 17459 redis_gcs_client.cc:147] RedisGcsClient::Connect finished with status OK
I0919 15:02:01.974119 17459 grpc_server.cc:60] driver server started, listening on port 35635.
E0919 15:02:02.547047 17459 raylet_client.cc:113] Retrying to connect to socket for pathname ./tmp/ray/session_2020-09-19_15-02-00_411896_17459/sockets/raylet (num_attempts = 1, num_retries = 5)
E0919 15:02:03.047868 17459 raylet_client.cc:113] Retrying to connect to socket for pathname ./tmp/ray/session_2020-09-19_15-02-00_411896_17459/sockets/raylet (num_attempts = 2, num_retries = 5)
E0919 15:02:03.550001 17459 raylet_client.cc:113] Retrying to connect to socket for pathname ./tmp/ray/session_2020-09-19_15-02-00_411896_17459/sockets/raylet (num_attempts = 3, num_retries = 5)
E0919 15:02:04.050578 17459 raylet_client.cc:113] Retrying to connect to socket for pathname ./tmp/ray/session_2020-09-19_15-02-00_411896_17459/sockets/raylet (num_attempts = 4, num_retries = 5)
F0919 15:02:04.551368 17459 raylet_client.cc:122] Could not connect to socket ./tmp/ray/session_2020-09-19_15-02-00_411896_17459/sockets/raylet
```

Can you give me some advice on how these mistakes come about?

Thank you~

**Comment by louiskirsch** [comment]
Seems like an OpenBLAS issue to me
```
OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 56: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 515042 current, 515042 max
```

Perhaps this helps?
https://stackoverflow.com/questions/51256738/multiple-instances-of-python-running-simultaneously-limited-to-35
