### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by sumwailiu** [timediv/metagenrl#7]
Traceback (most recent call last):
  File "/home/sumwailiu/miniconda3/envs/tf115/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/sumwailiu/miniconda3/envs/tf115/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 351, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/sumwailiu/miniconda3/envs/tf115/lib/python3.7/site-packages/ray/worker.py", line 2121, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray_worker (pid=1296, host=bc53eb4c8015)
  File "/home/sumwailiu/miniconda3/envs/tf115/lib/python3.7/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/sumwailiu/MetaGenRL/ray_experiments.py", line 115, in _train
    interaction_lengths, shortest_episodes, rewards = zip(*ray.get(simulation_objs))
ray.exceptions.RayTaskError(ValueError): ray_worker (pid=1297, host=bc53eb4c8015)
  File "/home/sumwailiu/MetaGenRL/ray_workers.py", line 384, in simulate
    ep_len, episode_reward, taken_actions = simulate_episode()
  File "/home/sumwailiu/MetaGenRL/ray_workers.py", line 362, in simulate_episode
    new_obs, r, d, _ = env.step(a)
ValueError: too many values to unpack (expected 4)

====
Here are the versions of my installed packages.
Package              Version

absl-py              1.4.0
ale-py               0.8.1
astor                0.8.1
async-timeout        4.0.2
attrs                23.1.0
box2d-py             2.3.5
certifi              2023.5.7
cffi                 1.15.1
charset-normalizer   3.1.0
click                8.1.3
cloudpickle          2.2.1
colorama             0.4.6
cycler               0.11.0
Cython               0.29.34
decorator            4.4.2
exceptiongroup       1.1.1
fasteners            0.18
filelock             3.12.0
fonttools            4.38.0
funcsigs             1.0.2
gast                 0.2.2
glfw                 2.5.9
google-pasta         0.2.0
grpcio               1.54.2
gym                  0.26.2
gym-notices          0.0.8
h5py                 2.10.0
idna                 3.4
imageio              2.28.1
imageio-ffmpeg       0.4.8
importlib-metadata   6.6.0
importlib-resources  5.12.0
iniconfig            2.0.0
jsonschema           4.17.3
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.4.4
lz4                  4.3.2
Markdown             3.4.3
MarkupSafe           2.1.2
matplotlib           3.5.3
moviepy              1.0.3
mujoco               2.1.2
mujoco-py            2.0.2.8
numpy                1.18.5
opencv-python        4.7.0.72
opt-einsum           3.3.0
packaging            23.1
Pillow               9.5.0
pip                  23.1.2
pkgutil_resolve_name 1.3.10
pluggy               1.0.0
proglog              0.1.10
protobuf             3.14.0
psutil               5.9.5
py                   1.11.0
pyarrow              0.13.0
pycparser            2.21
pygame               2.1.0
PyOpenGL             3.1.6
pyparsing            3.0.9
pyrsistent           0.19.3
pytest               7.0.1
python-dateutil      2.8.2
PyYAML               6.0
ray                  0.7.6
redis                4.5.5
requests             2.30.0
scipy                1.7.1
setuptools           67.7.2
six                  1.16.0
swig                 4.1.1
tensorboard          1.15.0
tensorflow-estimator 1.15.1
tensorflow-gpu       1.15.5
termcolor            2.3.0
tomli                2.0.1
tqdm                 4.65.0
typing_extensions    4.5.0
urllib3              2.0.2
Werkzeug             2.2.3
wheel                0.40.0
wrapt                1.15.0
zipp                 3.15.0

**Comment by louiskirsch** [comment]
You are using a too new version of gym I believe. Try these:
```
absl-py==0.9.0
astor==0.8.1
atari-py==0.2.6
attrs==19.3.0
box2d-py==2.3.8
cachetools==4.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
colorama==0.4.3
Cython==0.29.14
fasteners==0.15
filelock==3.0.12
funcsigs==1.0.2
future==0.18.2
gast==0.2.2
glfw==1.9.0
google-auth==1.10.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.26.0
gym==0.15.4
h5py==2.10.0
idna==2.8
imageio==2.6.1
importlib-metadata==1.3.0
jsonschema==3.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
lockfile==0.12.2
Markdown==3.1.1
monotonic==1.5
more-itertools==8.0.2
mujoco-py==2.0.2.9
numpy==1.18.0
oauthlib==3.1.0
opencv-python==4.1.2.30
opt-einsum==3.1.0
packaging==19.2
Pillow==7.0.0
pluggy==0.13.1
protobuf==3.11.2
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser==2.19
pyglet==1.3.2
pyparsing==2.4.6
pyrsistent==0.15.6
pytest==5.3.2
PyYAML==5.2
ray==0.7.6
redis==3.3.11
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
scipy==1.4.1
six==1.13.0
tabulate==0.8.6
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
urllib3==1.25.7
wcwidth==0.1.8
Werkzeug==0.16.0
wrapt==1.11.2
zipp==0.6.0
```
